

export const LOGIN_STRATEGIES = ['UNKNOWN', 'STANDARD', 'OTP', 'PASSCODE', 'ONE2MANY']

export const CONFIRM = ['UNDECIDED', 'PHONE', 'EMAIL']

export const RELATION_TYPES = ['UNREVEALED', 'BRANCH', 'REGION']